services:
  - type: web
    name: airesume-backend
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airesume-db
          property: connectionString
      - key: ADZUNA_API_KEY
        value: 2dcdd9b279ef39482ddce653263ce520
      - key: ADZUNA_APP_ID
        value: 20a4c4d7
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://airesume-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

  - type: web
    name: airesume-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://airesume-backend.onrender.com
    autoDeploy: true

databases:
  - name: airesume-db
    databaseName: airesume
    user: airesume 